function auraHighlightStyle() {
  const config = {
    name: 'aura',
    dark: true,
    background: '#21202e',
    foreground: '#edecee',
    selection: '#3d375e7f',
    cursor: '#a277ff',
    dropdownBackground: '#21202e',
    dropdownBorder: '#3b334b',
    activeLine: '#a394f033',
    matchingBracket: '#a394f033',
    keyword: '#a277ff',
    storage: '#a277ff',
    variable: '#edecee',
    parameter: '#edecee',
    function: '#ffca85',
    string: '#61ffca',
    constant: '#61ffca',
    type: '#82e2ff',
    class: '#82e2ff',
    number: '#61ffca',
    comment: '#6d6d6d',
    heading: '#a277ff',
    invalid: '#ff6767',
    regexp: '#61ffca',
  };
  return HighlightStyle.define([ 
    {tag: t.keyword, color: config.keyword},
    {tag: [t.name, t.deleted, t.character, t.macroName], color: config.variable},
    {tag: [t.propertyName], color: config.function},
    {tag: [t.processingInstruction, t.string, t.inserted, t.special(t.string)], color: config.string},
    {tag: [t.function(t.variableName), t.labelName], color: config.function},
    {tag: [t.color, t.constant(t.name), t.standard(t.name)], color: config.constant},
    {tag: [t.definition(t.name), t.separator], color: config.variable},
    {tag: [t.className], color: config.class},
    {tag: [t.number, t.changed, t.annotation, t.modifier, t.self, t.namespace], color: config.number},
    {tag: [t.typeName], color: config.type, fontStyle: config.type},
    {tag: [t.operator, t.operatorKeyword], color: config.keyword},
    {tag: [t.url, t.escape, t.regexp, t.link], color: config.regexp},
    {tag: [t.meta, t.comment], color: config.comment},
    {tag: t.strong, fontWeight: 'bold'},
    {tag: t.emphasis, fontStyle: 'italic'},
    {tag: t.link, textDecoration: 'underline'},
    {tag: t.heading, fontWeight: 'bold', color: config.heading},
    {tag: [t.atom, t.bool, t.special(t.variableName)], color: config.variable},
    {tag: t.invalid, color: config.invalid},
    {tag: t.strikethrough, textDecoration: 'line-through'},
  ]);
}
