function draculaHighlightStyle() {
  const config = {
    name: 'dracula',
    dark: true,
    background: '#282A36',
    foreground: '#F8F8F2',
    selection: '#44475A',
    cursor: '#F8F8F2',
    dropdownBackground: '#282A36',
    dropdownBorder: '#191A21',
    activeLine: '#44475A',
    matchingBracket: '#44475A',
    keyword: '#FF79C6',
    storage: '#FF79C6',
    variable: '#F8F8F2',
    parameter: '#F8F8F2',
    function: '#50FA7B',
    string: '#F1FA8C',
    constant: '#BD93F9',
    type: '#8BE9FD',
    class: '#8BE9FD',
    number: '#BD93F9',
    comment: '#6272A4',
    heading: '#BD93F9',
    invalid: '#FF5555',
    regexp: '#F1FA8C',
  };
  return HighlightStyle.define([ 
    {tag: t.keyword, color: config.keyword},
    {tag: [t.name, t.deleted, t.character, t.macroName], color: config.variable},
    {tag: [t.propertyName], color: config.function},
    {tag: [t.processingInstruction, t.string, t.inserted, t.special(t.string)], color: config.string},
    {tag: [t.function(t.variableName), t.labelName], color: config.function},
    {tag: [t.color, t.constant(t.name), t.standard(t.name)], color: config.constant},
    {tag: [t.definition(t.name), t.separator], color: config.variable},
    {tag: [t.className], color: config.class},
    {tag: [t.number, t.changed, t.annotation, t.modifier, t.self, t.namespace], color: config.number},
    {tag: [t.typeName], color: config.type, fontStyle: config.type},
    {tag: [t.operator, t.operatorKeyword], color: config.keyword},
    {tag: [t.url, t.escape, t.regexp, t.link], color: config.regexp},
    {tag: [t.meta, t.comment], color: config.comment},
    {tag: t.strong, fontWeight: 'bold'},
    {tag: t.emphasis, fontStyle: 'italic'},
    {tag: t.link, textDecoration: 'underline'},
    {tag: t.heading, fontWeight: 'bold', color: config.heading},
    {tag: [t.atom, t.bool, t.special(t.variableName)], color: config.variable},
    {tag: t.invalid, color: config.invalid},
    {tag: t.strikethrough, textDecoration: 'line-through'},
  ]);
}
