function highContrastLightHighlightStyle() {
  const config = {
    name: 'highContrastLight',
    dark: false,
    background: '#ffffff',
    foreground: '#292929',
    selection: '#0F4A85',
    cursor: '#292929',
    dropdownBackground: '#ffffff',
    dropdownBorder: '#0F4A85',
    activeLine: '#0F4A85',
    matchingBracket: '#0000',
    keyword: '#0F4A85',
    storage: '#0F4A85',
    variable: '#001080',
    parameter: '#001080',
    function: '#5e2cbc',
    string: '#0F4A85',
    constant: '#0F4A85',
    type: '#185E73',
    class: '#185E73',
    number: '#096d48',
    comment: '#515151',
    heading: '#0F4A85',
    invalid: '#B5200D',
    regexp: '#811F3F',
  };
  return HighlightStyle.define([ 
    {tag: t.keyword, color: config.keyword},
    {tag: [t.name, t.deleted, t.character, t.macroName], color: config.variable},
    {tag: [t.propertyName], color: config.function},
    {tag: [t.processingInstruction, t.string, t.inserted, t.special(t.string)], color: config.string},
    {tag: [t.function(t.variableName), t.labelName], color: config.function},
    {tag: [t.color, t.constant(t.name), t.standard(t.name)], color: config.constant},
    {tag: [t.definition(t.name), t.separator], color: config.variable},
    {tag: [t.className], color: config.class},
    {tag: [t.number, t.changed, t.annotation, t.modifier, t.self, t.namespace], color: config.number},
    {tag: [t.typeName], color: config.type, fontStyle: config.type},
    {tag: [t.operator, t.operatorKeyword], color: config.keyword},
    {tag: [t.url, t.escape, t.regexp, t.link], color: config.regexp},
    {tag: [t.meta, t.comment], color: config.comment},
    {tag: t.strong, fontWeight: 'bold'},
    {tag: t.emphasis, fontStyle: 'italic'},
    {tag: t.link, textDecoration: 'underline'},
    {tag: t.heading, fontWeight: 'bold', color: config.heading},
    {tag: [t.atom, t.bool, t.special(t.variableName)], color: config.variable},
    {tag: t.invalid, color: config.invalid},
    {tag: t.strikethrough, textDecoration: 'line-through'},
  ]);
}
