function materialLightHighlightStyle() {
  const config = {
    name: 'materialLight',
    dark: false,
    background: '#FAFAFA',
    foreground: '#90A4AE',
    selection: '#80CBC440',
    cursor: '#272727',
    dropdownBackground: '#FAFAFA',
    dropdownBorder: '#00000010',
    activeLine: '#CCD7DA50',
    matchingBracket: '#FAFAFA',
    keyword: '#39ADB5',
    storage: '#39ADB5',
    variable: '#90A4AE',
    parameter: '#90A4AE',
    function: '#6182B8',
    string: '#91B859',
    constant: '#39ADB5',
    type: '#E2931D',
    class: '#E2931D',
    number: '#F76D47',
    comment: '#90A4AE',
    heading: '#39ADB5',
    invalid: '#E5393570',
    regexp: '#91B859',
  };
  return HighlightStyle.define([ 
    {tag: t.keyword, color: config.keyword},
    {tag: [t.name, t.deleted, t.character, t.macroName], color: config.variable},
    {tag: [t.propertyName], color: config.function},
    {tag: [t.processingInstruction, t.string, t.inserted, t.special(t.string)], color: config.string},
    {tag: [t.function(t.variableName), t.labelName], color: config.function},
    {tag: [t.color, t.constant(t.name), t.standard(t.name)], color: config.constant},
    {tag: [t.definition(t.name), t.separator], color: config.variable},
    {tag: [t.className], color: config.class},
    {tag: [t.number, t.changed, t.annotation, t.modifier, t.self, t.namespace], color: config.number},
    {tag: [t.typeName], color: config.type, fontStyle: config.type},
    {tag: [t.operator, t.operatorKeyword], color: config.keyword},
    {tag: [t.url, t.escape, t.regexp, t.link], color: config.regexp},
    {tag: [t.meta, t.comment], color: config.comment},
    {tag: t.strong, fontWeight: 'bold'},
    {tag: t.emphasis, fontStyle: 'italic'},
    {tag: t.link, textDecoration: 'underline'},
    {tag: t.heading, fontWeight: 'bold', color: config.heading},
    {tag: [t.atom, t.bool, t.special(t.variableName)], color: config.variable},
    {tag: t.invalid, color: config.invalid},
    {tag: t.strikethrough, textDecoration: 'line-through'},
  ]);
}
