function monokaiDimmedHighlightStyle() {
  const config = {
    name: 'monokaiDimmed',
    dark: true,
    background: '#1e1e1e',
    foreground: '#c5c8c6',
    selection: '#676b7180',
    cursor: '#c07020',
    dropdownBackground: '#1e1e1e',
    dropdownBorder: '#454545',
    activeLine: '#303030',
    matchingBracket: '#303030',
    keyword: '#6089B4',
    storage: '#9872A2',
    variable: '#6089B4',
    parameter: '#6089B4',
    function: '#CE6700',
    string: '#9AA83A',
    constant: '#8080FF',
    type: '#9B0000',
    class: '#9B0000',
    number: '#6089B4',
    comment: '#9A9B99',
    heading: '#D0B344',
    invalid: '#FF0B00',
    regexp: '#9AA83A',
  };
  return HighlightStyle.define([ 
    {tag: t.keyword, color: config.keyword},
    {tag: [t.name, t.deleted, t.character, t.macroName], color: config.variable},
    {tag: [t.propertyName], color: config.function},
    {tag: [t.processingInstruction, t.string, t.inserted, t.special(t.string)], color: config.string},
    {tag: [t.function(t.variableName), t.labelName], color: config.function},
    {tag: [t.color, t.constant(t.name), t.standard(t.name)], color: config.constant},
    {tag: [t.definition(t.name), t.separator], color: config.variable},
    {tag: [t.className], color: config.class},
    {tag: [t.number, t.changed, t.annotation, t.modifier, t.self, t.namespace], color: config.number},
    {tag: [t.typeName], color: config.type, fontStyle: config.type},
    {tag: [t.operator, t.operatorKeyword], color: config.keyword},
    {tag: [t.url, t.escape, t.regexp, t.link], color: config.regexp},
    {tag: [t.meta, t.comment], color: config.comment},
    {tag: t.strong, fontWeight: 'bold'},
    {tag: t.emphasis, fontStyle: 'italic'},
    {tag: t.link, textDecoration: 'underline'},
    {tag: t.heading, fontWeight: 'bold', color: config.heading},
    {tag: [t.atom, t.bool, t.special(t.variableName)], color: config.variable},
    {tag: t.invalid, color: config.invalid},
    {tag: t.strikethrough, textDecoration: 'line-through'},
  ]);
}
