function solarizedDarkHighlightStyle() {
  const config = {
    name: 'solarizedDark',
    dark: true,
    background: '#002b36',
    foreground: '#93a1a1',
    selection: '#073642',
    cursor: '#839496',
    dropdownBackground: '#002b36',
    dropdownBorder: '#2aa19899',
    activeLine: '#073642',
    matchingBracket: '#073642',
    keyword: '#859900',
    storage: '#93A1A1',
    variable: '#839496',
    parameter: '#839496',
    function: '#268BD2',
    string: '#2AA198',
    constant: '#CB4B16',
    type: '#b58900',
    class: '#CB4B16',
    number: '#D33682',
    comment: '#657B83',
    heading: '#268BD2',
    invalid: '#ffeaea',
    regexp: '#D30102',
  };
  return HighlightStyle.define([ 
    {tag: t.keyword, color: config.keyword},
    {tag: [t.name, t.deleted, t.character, t.macroName], color: config.variable},
    {tag: [t.propertyName], color: config.function},
    {tag: [t.processingInstruction, t.string, t.inserted, t.special(t.string)], color: config.string},
    {tag: [t.function(t.variableName), t.labelName], color: config.function},
    {tag: [t.color, t.constant(t.name), t.standard(t.name)], color: config.constant},
    {tag: [t.definition(t.name), t.separator], color: config.variable},
    {tag: [t.className], color: config.class},
    {tag: [t.number, t.changed, t.annotation, t.modifier, t.self, t.namespace], color: config.number},
    {tag: [t.typeName], color: config.type, fontStyle: config.type},
    {tag: [t.operator, t.operatorKeyword], color: config.keyword},
    {tag: [t.url, t.escape, t.regexp, t.link], color: config.regexp},
    {tag: [t.meta, t.comment], color: config.comment},
    {tag: t.strong, fontWeight: 'bold'},
    {tag: t.emphasis, fontStyle: 'italic'},
    {tag: t.link, textDecoration: 'underline'},
    {tag: t.heading, fontWeight: 'bold', color: config.heading},
    {tag: [t.atom, t.bool, t.special(t.variableName)], color: config.variable},
    {tag: t.invalid, color: config.invalid},
    {tag: t.strikethrough, textDecoration: 'line-through'},
  ]);
}
