function tokyoNightHighlightStyle() {
  const config = {
    name: 'tokyoNight',
    dark: true,
    background: '#1a1b26',
    foreground: '#787c99',
    selection: '#515c7e40',
    cursor: '#c0caf5',
    dropdownBackground: '#1a1b26',
    dropdownBorder: '#787c99',
    activeLine: '#1e202e',
    matchingBracket: '#16161e',
    keyword: '#bb9af7',
    storage: '#bb9af7',
    variable: '#c0caf5',
    parameter: '#c0caf5',
    function: '#7aa2f7',
    string: '#9ece6a',
    constant: '#bb9af7',
    type: '#0db9d7',
    class: '#c0caf5',
    number: '#ff9e64',
    comment: '#444b6a',
    heading: '#89ddff',
    invalid: '#ff5370',
    regexp: '#b4f9f8',
  };
  return HighlightStyle.define([ 
    {tag: t.keyword, color: config.keyword},
    {tag: [t.name, t.deleted, t.character, t.macroName], color: config.variable},
    {tag: [t.propertyName], color: config.function},
    {tag: [t.processingInstruction, t.string, t.inserted, t.special(t.string)], color: config.string},
    {tag: [t.function(t.variableName), t.labelName], color: config.function},
    {tag: [t.color, t.constant(t.name), t.standard(t.name)], color: config.constant},
    {tag: [t.definition(t.name), t.separator], color: config.variable},
    {tag: [t.className], color: config.class},
    {tag: [t.number, t.changed, t.annotation, t.modifier, t.self, t.namespace], color: config.number},
    {tag: [t.typeName], color: config.type, fontStyle: config.type},
    {tag: [t.operator, t.operatorKeyword], color: config.keyword},
    {tag: [t.url, t.escape, t.regexp, t.link], color: config.regexp},
    {tag: [t.meta, t.comment], color: config.comment},
    {tag: t.strong, fontWeight: 'bold'},
    {tag: t.emphasis, fontStyle: 'italic'},
    {tag: t.link, textDecoration: 'underline'},
    {tag: t.heading, fontWeight: 'bold', color: config.heading},
    {tag: [t.atom, t.bool, t.special(t.variableName)], color: config.variable},
    {tag: t.invalid, color: config.invalid},
    {tag: t.strikethrough, textDecoration: 'line-through'},
  ]);
}
