function tomorrowNightBlueHighlightStyle() {
  const config = {
    name: 'tomorrowNightBlue',
    dark: true,
    background: '#002451',
    foreground: '#ffffff',
    selection: '#003f8e',
    cursor: '#ffffff',
    dropdownBackground: '#002451',
    dropdownBorder: '#454545',
    activeLine: '#00346e',
    matchingBracket: '#00346e',
    keyword: '#EBBBFF',
    storage: '#EBBBFF',
    variable: '#FF9DA4',
    parameter: '#FF9DA4',
    function: '#BBDAFF',
    string: '#D1F1A9',
    constant: '#FFC58F',
    type: '#FFEEAD',
    class: '#FFEEAD',
    number: '#FFC58F',
    comment: '#7285B7',
    heading: '#D1F1A9',
    invalid: '#a92049',
    regexp: '#D1F1A9',
  };
  return HighlightStyle.define([ 
    {tag: t.keyword, color: config.keyword},
    {tag: [t.name, t.deleted, t.character, t.macroName], color: config.variable},
    {tag: [t.propertyName], color: config.function},
    {tag: [t.processingInstruction, t.string, t.inserted, t.special(t.string)], color: config.string},
    {tag: [t.function(t.variableName), t.labelName], color: config.function},
    {tag: [t.color, t.constant(t.name), t.standard(t.name)], color: config.constant},
    {tag: [t.definition(t.name), t.separator], color: config.variable},
    {tag: [t.className], color: config.class},
    {tag: [t.number, t.changed, t.annotation, t.modifier, t.self, t.namespace], color: config.number},
    {tag: [t.typeName], color: config.type, fontStyle: config.type},
    {tag: [t.operator, t.operatorKeyword], color: config.keyword},
    {tag: [t.url, t.escape, t.regexp, t.link], color: config.regexp},
    {tag: [t.meta, t.comment], color: config.comment},
    {tag: t.strong, fontWeight: 'bold'},
    {tag: t.emphasis, fontStyle: 'italic'},
    {tag: t.link, textDecoration: 'underline'},
    {tag: t.heading, fontWeight: 'bold', color: config.heading},
    {tag: [t.atom, t.bool, t.special(t.variableName)], color: config.variable},
    {tag: t.invalid, color: config.invalid},
    {tag: t.strikethrough, textDecoration: 'line-through'},
  ]);
}
